### ISSUE TITLE
Problem connecting to a 1.21 NeoForge Server 

### ISSUE THREAD

**Issue by MarkapToGo** [Sonic2423/NeoForwarding#2]
I use your mod to connect a 1.21 NeoForge Server with a Velocity Server. Therefore I have [ambassador](https://modrinth.com/plugin/ambassador/version/1.4.4) installed on the velocity server.

**Velocity.toml:** https://mclo.gs/hIHHE56
**Installed Modpack on server:** [All The Mods 10](https://www.curseforge.com/minecraft/modpacks/all-the-mods-10)
**Installed Mod on NeoForge:** neoforwarding-1.0.0-1.21-NeoForge.jar
>> enableForwarding = true | online-mode: (in server.properties) false

Error Log on Velocity: https://mclo.gs/SJTna6g
Console - NeoForge: https://mclo.gs/h9oGswJ

**Comment by Sonic2423** [comment]
Ambassador is not intended for 1.21. Try without ambassador. Server hopping should also work without ambassador ("/server <name>"). If the error persists i will have a look at the logs etc.

**Comment by MarkapToGo** [comment]
Thank you for your answer. 
I have tried it without Ambassador, but the same problem persists... 
The errors that appear are still the same!

When stopping the server, I get this NeoForwarding Server: https://mclo.gs/Ckvz9mm

**Comment by Sonic2423** [comment]
This seems to be an issue with velocity. A limit (64) for known packets was introduced a couple months back which breaks some modded servers. removing this limit in velocity itself makes atm10 work with neoforwarding. in the attached screenshot i have added a packCount readout to velocity and removed the limit check:
![grafik](https://github.com/user-attachments/assets/164e68a6-c8bb-4952-a4ae-4dc9a0d7948f)

For the crash at server stop i have made another issue. i will fix this in all branches the coming days and add 1.21.1 support.

**Comment by Sonic2423** [comment]
Running velocity with -Dvelocity.max-known-packs=256 should fix your issue. If you ever encounter "too many known packets" in your velocity log again after the modpack grows you can alway increase the amount. Dont make it too high though as it is meant as a protective measure against DOS attacks (eg. increase the number by 16 and repeat until it works).

**Comment by MarkapToGo** [comment]
Thank you! This solved the problem!
