### ISSUE TITLE
Possible CrossStitch issue with ATM10 and Velocity

### ISSUE THREAD

**Issue by LevyWilson** [Sonic2423/NeoForwarding#9]
We've got a unique server setup at the moment. I have 5 servers as backends to a Velocity proxy. Two of them are 1.12.2 servers, so we're using legacy forwarding. ATM10 has 2 mods to make this work. One is Neoforwarding and another is a 1.21 Neoforge port of Bungeeforge for cross-server chat. Recently I've tried updating the server to 1.0 of ATM10, we've been running .20-.66 with little issue except when announce-proxy-commands is set to true in Velocity, OPs can't join so that's been set to false. We've also been stuck on version 416 of Velocity for some reason. Anything newer gives this same issue as with announce-proxy-commands being true. Now this issue happens with 1.0, so I think there's some kind of CrossStitch issue. Any advice would be greatly appreciated.

[2024-10-13-6.log](https://github.com/user-attachments/files/17354817/2024-10-13-6.log)

**Comment by Sonic2423** [comment]
The fix you are looking for will be out in version 1.2.0 of NeoForwarding. I have tested with ATM10-1.1
